id: P006660
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:13:55.698389
source_metadata:
  id: bdr:W1KG8313
  title: རྗེ་ངག་དབང་ཡོན་ཏན་བཟང་པོ་རྗེ་སུ་དྲན་པ།
  author: ''
  volumes:
    19f03b7e486942ecb2bb5f7d1f629e44:
      image_group_id: I1KG8491
      title: ''
      volume_number: 1
      total_pages: 76
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
