id: I32E9A321
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:15:05+00:00'
last_modified: '2022-06-08T06:21:02.899291+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8313
  title: རྗེ་ངག་དབང་ཡོན་ཏན་བཟང་པོ་རྗེ་སུ་དྲན་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E758:
      image_group_id: I1KG8491
      title: ''
      total_pages: 76
      order: 1
      base_file: E758.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
